%YAML 1.2
---

distribution_name: 'ArcExp'

internet_connection_required: yes

internet_checker_url: 'http://nmcheck.gnome.org/check_network_status.txt'

fixed_language: no

suggested_languages:
    - 'de'
    - 'en'
    - 'es'
    - 'fr'
    - 'nl'
    - 'uk'

welcome_page:
    logo    : '/usr/share/pixmaps/arcexp-logo.png'
    text    : 'Welcome to ArcExp!'
    usage   : yes

minimum_disk_size: 20
offer_disk_encryption: yes

skip_user: no
skip_locale: no

# List of software that can additionally be selected for installation.
# Each packages requires all fields to be set.
#
# package         string  Forwarded to the installation script as is.
# suggested       bool    Optional. Whether installation defaults to yes.
# name_LC         string  Name presented to user. Translatable.
#                         If no (English) name is available, it will only
#                         be shown for translated languages.
# description_LC  string  Optional. Description presented to user. Translatable.
# icon_path       string  Optional. Absolute path to icon to be displayed.
#
# Default: [], suggested: False, description: '', icon_path: fallback icon
additional_software:
     - name           : 'Firefox'
       name_de        : 'Firefox'
       description    : 'Popular Web Browser from Mozilla'
       description_de : 'Beliebter Internet-Browser von Mozilla'
       icon_path      : '/etc/os-installer/icons/firefox.png'
       keyword        : 'firefox'
       suggested      : yes
     - name           : 'LibreWolf'
       name_de        : 'LibreWolf'
       description    : 'Popular Web Browser from the LibreWolf Community'
       description_de : 'Beliebter Internet-Browser von the LibreWolf Community'
       icon_path      : '/etc/os-installer/icons/librewolf.png'
       keyword        : 'LibreWolf'
       suggested      : yes
     - name           : 'Brave'
       name_de        : 'Brave'
       description    : 'Popular Web Browser from Brave Software'
       description_de : 'Beliebter Internet-Browser von Brave Software'
       icon_path      : '/etc/os-installer/icons/brave.png'
       keyword        : 'brave'
       suggested      : yes
     - name           : 'AUR helpers'
       description    : 'Select your desired AUR helper. Skip if unsure what to pick'
       icon_path      : '/etc/os-installer/icons/options-symbolic.svg'
       options        :
         - option     : 'yay'
         - name       : 'yay' 
           option     : 'paru'
           name       : 'paru'
         - option     : 'pikaur'
           name       : 'pikaur'

# Upon failure an option to search for help on the internet is given.
# The url this leads to can be defined here. The squiggly brackets are
# replaced with the os-installer version.
#
# Default: 'https://duckduckgo.com/?q="os-installer {}"+"failed installation"'
failure_help_url: 'https://support.dist.ro/new_issue?q="failed"+"os-installer {}"'

browser_cmd: 'firefox'
disks_cmd  : 'gnome-disks'
wifi_cmd   : 'gnome-control-center network'
